#pragma once
enum PLMessageIDTypes
{
	ID_TIMEOFDAY = 134,
	ID_CARCONTROLLER_FULLSTATE,
	ID_CARCONTROLLER_MAKEMEOWNER,
	ID_CARCONTROLLER_RELEASEOWNERSHIP,
	ID_CARCONTROLLER_OWNERSHIP,
	ID_CARCONTROLLER_UPDATE,
	ID_CHARACTERCONTROLLER_FULLSTATE,
	ID_CHARACTERCONTROLLER_UPDATE,
	ID_CHARACTERCONTROLLER_ENTERVEHICLE
};